type: gitlab_vulnerability
status:
  stability:
    logs: beta
  supported: true

config:
  paths:
    description: Single GitLab project or group to monitor
    type: list
    element:
      type: object
      properties:
        id:
          type: string
          description: GitLab project or group ID
        type:
          type: string
          enum: [project, group]
          description: Type of GitLab entity to monitor

  base_url:
    type: string
    default: "https://gitlab.com"
    description: GitLab instance URL

  token:
    type: string
    description: GitLab API token with read_api scope

  poll_interval:
    type: duration
    default: 5m
    description: How often to check for new vulnerabilities

  export_timeout:
    type: duration
    default: 15m
    description: Maximum time to wait for export completion

logs:
  vulnerability:
    description: A vulnerability finding from GitLab
    type: log_record
    severity_number: INFO
    body_type: string
    attributes:
      vulnerability.id:
        type: string
        description: Unique identifier for the vulnerability
      vulnerability.title:
        type: string
        description: Title of the vulnerability
      vulnerability.description:
        type: string
        description: Detailed description of the vulnerability
      vulnerability.severity:
        type: string
        enum: [critical, high, medium, low, unknown]
        description: Severity level of the vulnerability
      vulnerability.status:
        type: string
        enum: [detected, confirmed, resolved, dismissed]
        description: Current status of the vulnerability

resource_attributes:
  gitlab.project.id:
    description: The GitLab project ID
    type: string
    enabled: true
  gitlab.group.id:
    description: The GitLab group ID
    type: string
    enabled: true
  gitlab.export.id:
    description: The vulnerability export ID
    type: string
    enabled: true

attributes:
  vulnerability.id:
    description: The vulnerability ID
    type: string
  vulnerability.title:
    description: The vulnerability title
    type: string
  vulnerability.description:
    description: Detailed description of the vulnerability
    type: string
  vulnerability.state:
    description: Current state (detected, confirmed, dismissed, resolved)
    type: string
  vulnerability.severity:
    description: Severity level (critical, high, medium, low, info)
    type: string
  vulnerability.confidence:
    description: Confidence level of the finding
    type: string
  vulnerability.report_type:
    description: Type of security report
    type: string
  vulnerability.project_name:
    description: Name of the project
    type: string
  vulnerability.project_id:
    description: GitLab project ID
    type: string
  vulnerability.scanner:
    description: Security scanner that detected the vulnerability
    type: string
  vulnerability.scanner_id:
    description: ID of the scanner
    type: string
  vulnerability.finding_id:
    description: ID of the finding
    type: string
  vulnerability.identifiers:
    description: List of vulnerability identifiers (CVE, CWE, etc)
    type: string
  vulnerability.project_default_branch:
    description: Default branch of the project
    type: string
  vulnerability.solution:
    description: Suggested solution for the vulnerability
    type: string
  vulnerability.file:
    description: Affected file path
    type: string
  vulnerability.line:
    description: Line number where vulnerability was found
    type: string
  vulnerability.location_link:
    description: Link to vulnerability location
    type: string
  vulnerability.location_fingerprint:
    description: Fingerprint of vulnerability location
    type: string
  vulnerability.tracking_status:
    description: Status of vulnerability tracking
    type: string
  vulnerability.links:
    description: Related links
    type: string
  vulnerability.remediations:
    description: Suggested remediations
    type: string
  vulnerability.evidence:
    description: Supporting evidence
    type: string
  vulnerability.assets:
    description: Affected assets
    type: string
  vulnerability.discovered_at:
    description: When the vulnerability was discovered
    type: string
  vulnerability.confirmed_at:
    description: When the vulnerability was confirmed
    type: string
  vulnerability.resolved_at:
    description: When the vulnerability was resolved
    type: string
  vulnerability.dismissed_at:
    description: When the vulnerability was dismissed
    type: string
  vulnerability.dismissal_reason:
    description: Reason for dismissal
    type: string
  vulnerability.dismissal_comment:
    description: Comment explaining dismissal
    type: string

pipelines:
  logs:
    receivers: [gitlab_vulnerability] 